/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import static demo.MinMaxCategoryPlotDemo1.createChart;
import java.awt.Dimension;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Alba Proyecto
 */
public class Diagrama_momento extends javax.swing.JFrame {

    private double[] eje_x;
    private double[] eje_y;
    private double altura_muro;
    private double posicion_as;
    private double posicion_baston1;
    private double posicion_baston2;
    private double long_baston1;
    private double long_baston2;

    /**
     * Creates new form Frame
     */
    public Diagrama_momento(double[] eje_x, double[] eje_y, double altura_muro, double posicion_as, double posicion_baston1, double posicion_baston2, double long_baston1, double long_baston2) {
        this.eje_x = eje_x;
        this.eje_y = eje_y;
        this.altura_muro = altura_muro;
        this.posicion_as = posicion_as;
        this.posicion_baston1 = posicion_baston1;
        this.posicion_baston2 = posicion_baston2;
        this.long_baston1=long_baston1;
        this.long_baston2=long_baston2;

        setBounds(700, 200, 700, 500);
        String SITIO_1 = "PRIMERO";
        String SITIO_2 = "SEGUNDO";

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        XYSeriesCollection xy = new XYSeriesCollection();
        XYSeries serie1 = new XYSeries("Curva de Momentos");
        XYSeries serie2 = new XYSeries("Acero corrido");
        XYSeries serie3 = new XYSeries("Bastón1");
        XYSeries serie4 = new XYSeries("Bastón2");

        //aqui trazamos la curva
        for (int i = 0; i < eje_x.length; i++) {
            serie1.add(eje_x[i], eje_y[i]);
        }

//        for(int i=0; i<eje_x.length; i++){
//            serie2.add(eje_y[i],eje_x[i]);
//        }
        //aqui trazamos el acero corrido
        serie2.add(posicion_as, 0);
        serie2.add(posicion_as, altura_muro);
        
        xy.addSeries(serie1);
        xy.addSeries(serie2);

        //aqui trazamos baston1
        if (posicion_baston1 != 0) {
            serie3.add(posicion_baston1, 0);
            serie3.add(posicion_baston1, long_baston1);
            xy.addSeries(serie3);
        }
        
        if(posicion_baston2!=0){
            serie4.add(posicion_baston2,0);
            serie4.add(posicion_baston2,long_baston2);
            xy.addSeries(serie4);
        }

        //mi example
        final JFreeChart mi_gr = ChartFactory.createXYLineChart("Diagrama de Momentos", "datos_x", "datos_y", xy);
        //final JFreeChart mi_gr1=ChartFactory.createXYLineChart("Otra", "en_x", "en_y", xy, PlotOrientation.HORIZONTAL, true, true, true);

        final JFreeChart chart = createChart(dataset);
        final ChartPanel chartPanel = new ChartPanel(chart);
        final ChartPanel chartPanel1 = new ChartPanel(mi_gr);
        //chartPanel.setPreferredSize(new Dimension(500, 270));
        //chartPanel.setEnforceFileExtensions(false);
        chartPanel1.setPreferredSize(new Dimension(500, 270));
        chartPanel1.setEnforceFileExtensions(false);

        //setContentPane(chartPanel);
        setContentPane(chartPanel1);

        setDefaultCloseOperation(/*EXIT_ON_CLOSE*/DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Diagrama_momento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Diagrama_momento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Diagrama_momento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Diagrama_momento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Diagrama_momento().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
