/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import clases.Proyecto;
import java.text.ParseException;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Alba Proyecto
 */
public class Ventana_calculo1 extends javax.swing.JInternalFrame {

//    private final MaskFormatter mask;
//    private final MaskFormatter mask1;
//    private final MaskFormatter mask2;
//    private final MaskFormatter mask3;
//    private final MaskFormatter mask4;
/**
     * Creates new form Ventana_calculo
     */
        //private String nombre_py;
        private Proyecto py;

    public Ventana_calculo1(Proyecto py)  {//revisar esta excepcion*************************
        this.py = py;
        setTitle(this.py.getNombre_py());
        
        initComponents();
        setBounds(0, 0, 1850, 1000);
        //setPreferredSize(getMaximumSize());
        poblar_combo();
    }

    public Proyecto getPy() {
        return py;
    }

    public void setPy(Proyecto py) {
        this.py = py;
    }
    
    public void poblar_combo(){
        for(int i=0; i<py.getLista().size(); i++){
            combo1.addItem(py.getLista().get(i).getLista_muro().get(0));
        }
    }  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        combo1 = new javax.swing.JComboBox<>();
        jPanel31 = new javax.swing.JPanel();
        aceptar_1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel27 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        fi1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        gamma1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        sc = new javax.swing.JTextField();
        jLabel_ka1 = new javax.swing.JLabel();
        ka1 = new javax.swing.JTextField();
        jLabel_kp1 = new javax.swing.JLabel();
        kp1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        fi2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        gamma2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        qad = new javax.swing.JTextField();
        jLabel_kp2 = new javax.swing.JLabel();
        kp2 = new javax.swing.JTextField();
        jLabel_ka2 = new javax.swing.JLabel();
        ka2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        h1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        h2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        d2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        d1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        l1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        var_e = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        l2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        l3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        wp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        mwp = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        wa = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        mwa = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        p_propio = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        mpp = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        fs_v = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        constante1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        alpha = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        sum_v = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        fs_desliz = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        constante2 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        q_max = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        qad_espejo = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        q_min = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        next_to_qmin = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel108 = new javax.swing.JLabel();
        fc = new javax.swing.JTextField();
        jLabel109 = new javax.swing.JLabel();
        beta1 = new javax.swing.JTextField();
        jLabel110 = new javax.swing.JLabel();
        r = new javax.swing.JComboBox<>();
        jLabel111 = new javax.swing.JLabel();
        rho_bal = new javax.swing.JTextField();
        jLabel112 = new javax.swing.JLabel();
        fy = new javax.swing.JTextField();
        jLabel113 = new javax.swing.JLabel();
        rho_max = new javax.swing.JTextField();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel117 = new javax.swing.JLabel();
        kv = new javax.swing.JTextField();
        jLabel120 = new javax.swing.JLabel();
        pae = new javax.swing.JTextField();
        jLabel124 = new javax.swing.JLabel();
        kh = new javax.swing.JTextField();
        jLabel123 = new javax.swing.JLabel();
        pa = new javax.swing.JTextField();
        jLabel119 = new javax.swing.JLabel();
        beta = new javax.swing.JTextField();
        jLabel121 = new javax.swing.JLabel();
        variacion_pae = new javax.swing.JTextField();
        jLabel122 = new javax.swing.JLabel();
        delta = new javax.swing.JTextField();
        jLabel118 = new javax.swing.JLabel();
        m = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        varillas1 = new javax.swing.JComboBox<>();
        jLabel69 = new javax.swing.JLabel();
        separacion1 = new javax.swing.JComboBox<>();
        jLabel54 = new javax.swing.JLabel();
        fi_f = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        as1 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        fi_v = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        fi_mr1 = new javax.swing.JTextField();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        varillas2 = new javax.swing.JComboBox<>();
        jLabel75 = new javax.swing.JLabel();
        separacion2 = new javax.swing.JComboBox<>();
        jLabel78 = new javax.swing.JLabel();
        as2 = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        ld_propuesto1 = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        ld1 = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        fi_mr2 = new javax.swing.JTextField();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        varillas3 = new javax.swing.JComboBox<>();
        jLabel93 = new javax.swing.JLabel();
        separacion3 = new javax.swing.JComboBox<>();
        jLabel96 = new javax.swing.JLabel();
        as3 = new javax.swing.JTextField();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        ld_propuesto2 = new javax.swing.JTextField();
        jLabel100 = new javax.swing.JLabel();
        ld2 = new javax.swing.JTextField();
        jLabel101 = new javax.swing.JLabel();
        fi_mr3 = new javax.swing.JTextField();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        varillas4 = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        separacion4 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        as4 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel125 = new javax.swing.JLabel();
        sum_fi_mr = new javax.swing.JTextField();
        jLabel126 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        m_max = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel127 = new javax.swing.JLabel();
        fi_vc = new javax.swing.JTextField();
        jLabel128 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        v_max = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        momento = new javax.swing.JRadioButton();
        cortante = new javax.swing.JRadioButton();
        mostrar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        aceptar1 = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        combo_almacen = new javax.swing.JComboBox<>();
        jPanel20 = new javax.swing.JPanel();
        guardar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();

        jLabel15.setText("jLabel13");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel29.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de edición", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel29.setLayout(new javax.swing.BoxLayout(jPanel29, javax.swing.BoxLayout.X_AXIS));

        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel30.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel30.add(combo1);

        jPanel29.add(jPanel30);

        jPanel31.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel31.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        aceptar_1.setText("Aceptar");
        jPanel31.add(aceptar_1);

        jPanel29.add(jPanel31);

        getContentPane().add(jPanel29);

        jPanel27.setLayout(new javax.swing.BoxLayout(jPanel27, javax.swing.BoxLayout.Y_AXIS));

        jPanel25.setLayout(new javax.swing.BoxLayout(jPanel25, javax.swing.BoxLayout.X_AXIS));

        jPanel24.setLayout(new javax.swing.BoxLayout(jPanel24, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suelo activo 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setLayout(new java.awt.GridLayout(6, 2, 2, 2));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("ϕ1");
        jPanel3.add(jLabel19);

        fi1.setText("30.0");
        jPanel3.add(fi1);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("γ1");
        jPanel3.add(jLabel20);

        gamma1.setText("1.75");
        jPanel3.add(gamma1);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Sc");
        jPanel3.add(jLabel21);

        sc.setText("5.0");
        jPanel3.add(sc);

        jLabel_ka1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ka1.setText("Ka");
        jPanel3.add(jLabel_ka1);

        ka1.setEditable(false);
        ka1.setBackground(new java.awt.Color(204, 204, 204));
        ka1.setText("1.0");
        jPanel3.add(ka1);

        jLabel_kp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_kp1.setText("Kp");
        jPanel3.add(jLabel_kp1);

        kp1.setEditable(false);
        kp1.setBackground(new java.awt.Color(204, 204, 204));
        kp1.setText("1.0");
        jPanel3.add(kp1);
        jPanel3.add(jLabel24);
        jPanel3.add(jLabel31);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suelo pasivo 2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel4.setLayout(new java.awt.GridLayout(6, 2, 2, 2));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("ϕ2");
        jPanel4.add(jLabel25);

        fi2.setText("30.0");
        jPanel4.add(fi2);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("γ2");
        jPanel4.add(jLabel26);

        gamma2.setText("1.75");
        jPanel4.add(gamma2);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("C'");
        jPanel4.add(jLabel27);

        c.setText("0.0");
        jPanel4.add(c);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Qad-[tonnef/m²]");
        jPanel4.add(jLabel28);

        qad.setText("20.7");
        jPanel4.add(qad);

        jLabel_kp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_kp2.setText("Kp");
        jPanel4.add(jLabel_kp2);

        kp2.setEditable(false);
        kp2.setBackground(new java.awt.Color(204, 204, 204));
        kp2.setText("0.0");
        jPanel4.add(kp2);

        jLabel_ka2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ka2.setText("Ka");
        jPanel4.add(jLabel_ka2);

        ka2.setEditable(false);
        ka2.setBackground(new java.awt.Color(204, 204, 204));
        ka2.setText("0.0");
        jPanel4.add(ka2);

        jPanel1.add(jPanel4);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Geometría", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setLayout(new java.awt.GridLayout(6, 4, 2, 2));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("h1-[m]");
        jPanel2.add(jLabel1);

        h1.setText("3.0");
        jPanel2.add(h1);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("a-[m]");
        jPanel2.add(jLabel3);

        a1.setText("0.35");
        jPanel2.add(a1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("h2-[m]");
        jPanel2.add(jLabel2);

        h2.setText("0.5");
        jPanel2.add(h2);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("d2-[m]");
        jPanel2.add(jLabel4);

        d2.setEditable(false);
        d2.setBackground(new java.awt.Color(204, 204, 204));
        d2.setText("0.2");
        jPanel2.add(d2);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("d1-[m]");
        jPanel2.add(jLabel6);

        d1.setText("0.0");
        jPanel2.add(d1);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("l1-[m]");
        jPanel2.add(jLabel7);

        l1.setText("1.20");
        jPanel2.add(l1);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("e-[m]");
        jPanel2.add(jLabel5);

        var_e.setText("0.2");
        jPanel2.add(var_e);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("l2-[m]");
        jPanel2.add(jLabel8);

        l2.setEditable(false);
        l2.setBackground(new java.awt.Color(204, 204, 204));
        l2.setText("0.35");
        jPanel2.add(l2);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel9);
        jPanel2.add(jLabel11);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("l3-[m]");
        jPanel2.add(jLabel10);

        l3.setText("0.5");
        jPanel2.add(l3);
        jPanel2.add(jLabel12);
        jPanel2.add(jLabel14);
        jPanel2.add(jLabel16);
        jPanel2.add(jLabel18);

        jPanel1.add(jPanel2);

        jPanel24.add(jPanel1);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Revisión por volteo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel6.setLayout(new java.awt.GridLayout(4, 4, 2, 2));

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Wp");
        jPanel6.add(jLabel34);

        wp.setEditable(false);
        wp.setBackground(new java.awt.Color(204, 204, 204));
        wp.setText("1.0");
        jPanel6.add(wp);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("MWp");
        jPanel6.add(jLabel13);

        mwp.setEditable(false);
        mwp.setBackground(new java.awt.Color(204, 204, 204));
        mwp.setText("1.0");
        jPanel6.add(mwp);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Wa");
        jPanel6.add(jLabel17);

        wa.setEditable(false);
        wa.setBackground(new java.awt.Color(204, 204, 204));
        wa.setText("1.0");
        jPanel6.add(wa);

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("MWa");
        jPanel6.add(jLabel40);

        mwa.setEditable(false);
        mwa.setBackground(new java.awt.Color(204, 204, 204));
        mwa.setText("1.0");
        jPanel6.add(mwa);

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("P propio");
        jPanel6.add(jLabel36);

        p_propio.setEditable(false);
        p_propio.setBackground(new java.awt.Color(204, 204, 204));
        p_propio.setText("1.0");
        jPanel6.add(p_propio);

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Mpp");
        jPanel6.add(jLabel39);

        mpp.setEditable(false);
        mpp.setBackground(new java.awt.Color(204, 204, 204));
        mpp.setText("1.0");
        jPanel6.add(mpp);

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Fs volteo");
        jPanel6.add(jLabel35);

        fs_v.setEditable(false);
        fs_v.setBackground(new java.awt.Color(204, 204, 204));
        fs_v.setText("1.0");
        jPanel6.add(fs_v);

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText(">=");
        jPanel6.add(jLabel41);

        constante1.setEditable(false);
        constante1.setBackground(new java.awt.Color(204, 204, 204));
        constante1.setText("3.0");
        jPanel6.add(constante1);

        jPanel5.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Revisión por deslizamiento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel7.setLayout(new java.awt.GridLayout(4, 4, 2, 2));

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("α");
        jPanel7.add(jLabel42);

        alpha.setText("0");
        jPanel7.add(alpha);

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel43);

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel44);

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Σv");
        jPanel7.add(jLabel45);

        sum_v.setEditable(false);
        sum_v.setBackground(new java.awt.Color(204, 204, 204));
        sum_v.setText("1.0");
        jPanel7.add(sum_v);

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel46);

        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel47);

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Fs");
        jPanel7.add(jLabel48);

        fs_desliz.setEditable(false);
        fs_desliz.setBackground(new java.awt.Color(204, 204, 204));
        fs_desliz.setText("1.0");
        jPanel7.add(fs_desliz);

        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText(">=");
        jPanel7.add(jLabel49);

        constante2.setEditable(false);
        constante2.setBackground(new java.awt.Color(204, 204, 204));
        constante2.setText("1.5");
        jPanel7.add(constante2);

        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel50);

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel51);

        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel52);

        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel53);

        jPanel5.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Revisión por capacidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel8.setLayout(new java.awt.GridLayout(4, 4, 2, 2));

        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Qmax-[tonnef/m²]");
        jPanel8.add(jLabel55);

        q_max.setEditable(false);
        q_max.setBackground(new java.awt.Color(204, 204, 204));
        q_max.setText("0.0");
        jPanel8.add(q_max);

        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("<=");
        jPanel8.add(jLabel56);

        qad_espejo.setEditable(false);
        qad_espejo.setBackground(new java.awt.Color(204, 204, 204));
        qad_espejo.setText("0.0");
        jPanel8.add(qad_espejo);

        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Qmin-[kgf/m²]");
        jPanel8.add(jLabel57);

        q_min.setEditable(false);
        q_min.setBackground(new java.awt.Color(204, 204, 204));
        q_min.setText("0.0");
        jPanel8.add(q_min);

        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText(">=");
        jPanel8.add(jLabel58);

        next_to_qmin.setEditable(false);
        next_to_qmin.setBackground(new java.awt.Color(204, 204, 204));
        next_to_qmin.setText("0.0");
        jPanel8.add(next_to_qmin);
        jPanel8.add(jLabel59);
        jPanel8.add(jLabel60);
        jPanel8.add(jLabel61);
        jPanel8.add(jLabel62);
        jPanel8.add(jLabel63);
        jPanel8.add(jLabel64);
        jPanel8.add(jLabel65);
        jPanel8.add(jLabel66);

        jPanel5.add(jPanel8);

        jPanel24.add(jPanel5);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.X_AXIS));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Diseño de muro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel15.setLayout(new java.awt.GridLayout(4, 4, 2, 2));

        jLabel108.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel108.setText("f´c");
        jPanel15.add(jLabel108);

        fc.setText("250");
        jPanel15.add(fc);

        jLabel109.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel109.setText("β1");
        jPanel15.add(jLabel109);

        beta1.setEditable(false);
        beta1.setBackground(new java.awt.Color(204, 204, 204));
        beta1.setText("1.0");
        jPanel15.add(beta1);

        jLabel110.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel110.setText("r");
        jPanel15.add(jLabel110);

        r.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2.5 cm", "5.0 cm", "7.5 cm" }));
        jPanel15.add(r);

        jLabel111.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel111.setText("ρ bal");
        jPanel15.add(jLabel111);

        rho_bal.setEditable(false);
        rho_bal.setBackground(new java.awt.Color(204, 204, 204));
        rho_bal.setText("1.0");
        jPanel15.add(rho_bal);

        jLabel112.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel112.setText("fy");
        jPanel15.add(jLabel112);

        fy.setText("4220");
        jPanel15.add(fy);

        jLabel113.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel113.setText("ρ max");
        jPanel15.add(jLabel113);

        rho_max.setEditable(false);
        rho_max.setBackground(new java.awt.Color(204, 204, 204));
        rho_max.setText("1.0");
        jPanel15.add(rho_max);

        jLabel114.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel15.add(jLabel114);
        jPanel15.add(jLabel115);
        jPanel15.add(jLabel116);
        jPanel15.add(jLabel131);

        jPanel11.add(jPanel15);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empuje activo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel16.setLayout(new java.awt.GridLayout(4, 4, 2, 2));

        jLabel117.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel117.setText("Kv");
        jPanel16.add(jLabel117);

        kv.setText("0.0");
        jPanel16.add(kv);

        jLabel120.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel120.setText("Pae");
        jPanel16.add(jLabel120);

        pae.setEditable(false);
        pae.setBackground(new java.awt.Color(204, 204, 204));
        pae.setText("1.0");
        jPanel16.add(pae);

        jLabel124.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel124.setText("Kh");
        jPanel16.add(jLabel124);

        kh.setText("0.2");
        jPanel16.add(kh);

        jLabel123.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel123.setText("Pa");
        jPanel16.add(jLabel123);

        pa.setEditable(false);
        pa.setBackground(new java.awt.Color(204, 204, 204));
        pa.setText("1.0");
        jPanel16.add(pa);

        jLabel119.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel119.setText("β");
        jPanel16.add(jLabel119);

        beta.setText("90");
        jPanel16.add(beta);

        jLabel121.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel121.setText("ΔPae");
        jPanel16.add(jLabel121);

        variacion_pae.setEditable(false);
        variacion_pae.setBackground(new java.awt.Color(204, 204, 204));
        variacion_pae.setText("1.0");
        jPanel16.add(variacion_pae);

        jLabel122.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel122.setText("δ");
        jPanel16.add(jLabel122);

        delta.setText("0.0");
        jPanel16.add(delta);

        jLabel118.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel118.setText("M");
        jPanel16.add(jLabel118);

        m.setEditable(false);
        m.setBackground(new java.awt.Color(204, 204, 204));
        m.setText("1.0");
        jPanel16.add(m);

        jPanel11.add(jPanel16);

        jPanel24.add(jPanel11);

        jPanel25.add(jPanel24);

        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gráfico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/mb_2.jpg"))); // NOI18N
        jLabel22.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel26.add(jLabel22);

        jPanel25.add(jPanel26);

        jPanel27.add(jPanel25);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.X_AXIS));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acero corrido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel12.setLayout(new java.awt.GridLayout(4, 4, 2, 2));

        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("Varillas");
        jPanel12.add(jLabel68);

        varillas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1#3 = 0.71 cm²", "1#4 = 1.27 cm²", "1#5= 1.98 cm²", "1#6 = 2.85 cm² ", "1#8 = 5.07 cm²", "1#10 = 7.92 cm²", "1#12 = 11.40 cm²" }));
        jPanel12.add(varillas1);

        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("Separación");
        jPanel12.add(jLabel69);

        separacion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2.5 cm", "5.0 cm", "7.5 cm", "10.0 cm", "12.5 cm", "15.0 cm", "17.5 cm", "20.0 cm", "22.5 cm", "25.0 cm", "27.5 cm", "30.0 cm" }));
        jPanel12.add(separacion1);

        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("ϕf");
        jPanel12.add(jLabel54);

        fi_f.setEditable(false);
        fi_f.setBackground(new java.awt.Color(204, 204, 204));
        fi_f.setText("0.9");
        jPanel12.add(fi_f);

        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("As");
        jPanel12.add(jLabel70);

        as1.setEditable(false);
        as1.setBackground(new java.awt.Color(204, 204, 204));
        as1.setText("1.0");
        jPanel12.add(as1);

        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("ϕv");
        jPanel12.add(jLabel67);

        fi_v.setEditable(false);
        fi_v.setBackground(new java.awt.Color(204, 204, 204));
        fi_v.setText("0.75");
        jPanel12.add(fi_v);

        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("ϕMr");
        jPanel12.add(jLabel71);

        fi_mr1.setEditable(false);
        fi_mr1.setBackground(new java.awt.Color(204, 204, 204));
        fi_mr1.setText("1.0");
        jPanel12.add(fi_mr1);
        jPanel12.add(jLabel132);
        jPanel12.add(jLabel133);
        jPanel12.add(jLabel134);
        jPanel12.add(jLabel135);

        jPanel10.add(jPanel12);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bastón 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel13.setLayout(new java.awt.GridLayout(4, 4, 2, 2));

        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("Varillas");
        jPanel13.add(jLabel72);

        varillas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no se necesita", "1#3 = 0.71 cm²", "1#4 = 1.27 cm²", "1#5= 1.98 cm²", "1#6 = 2.85 cm² ", "1#8 = 5.07 cm²", "1#10 = 7.92 cm²", "1#12 = 11.40 cm²" }));
        jPanel13.add(varillas2);

        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("Separación");
        jPanel13.add(jLabel75);

        separacion2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2.5 cm", "5.0 cm", "7.5 cm", "10.0 cm", "12.5 cm", "15.0 cm", "17.5 cm", "20.0 cm", "22.5 cm", "25.0 cm", "27.5 cm", "30.0 cm" }));
        jPanel13.add(separacion2);

        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel78.setText("As");
        jPanel13.add(jLabel78);

        as2.setEditable(false);
        as2.setBackground(new java.awt.Color(204, 204, 204));
        as2.setText("1.0");
        jPanel13.add(as2);
        jPanel13.add(jLabel79);
        jPanel13.add(jLabel80);

        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel81.setText("Ld propuesto");
        jPanel13.add(jLabel81);

        ld_propuesto1.setEditable(false);
        ld_propuesto1.setBackground(new java.awt.Color(204, 204, 204));
        ld_propuesto1.setText("1.0");
        jPanel13.add(ld_propuesto1);

        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel82.setText("Ld");
        jPanel13.add(jLabel82);

        ld1.setText("1.0");
        jPanel13.add(ld1);

        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel83.setText("ϕMr");
        jPanel13.add(jLabel83);

        fi_mr2.setEditable(false);
        fi_mr2.setBackground(new java.awt.Color(204, 204, 204));
        fi_mr2.setText("1.0");
        jPanel13.add(fi_mr2);
        jPanel13.add(jLabel84);
        jPanel13.add(jLabel85);

        jPanel10.add(jPanel13);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bastón 2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel14.setLayout(new java.awt.GridLayout(4, 4, 2, 2));

        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel90.setText("Varillas");
        jPanel14.add(jLabel90);

        varillas3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no se necesita", "1#3 = 0.71 cm²", "1#4 = 1.27 cm²", "1#5= 1.98 cm²", "1#6 = 2.85 cm² ", "1#8 = 5.07 cm²", "1#10 = 7.92 cm²", "1#12 = 11.40 cm²" }));
        jPanel14.add(varillas3);

        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel93.setText("Separación");
        jPanel14.add(jLabel93);

        separacion3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2.5 cm", "5.0 cm", "7.5 cm", "10.0 cm", "12.5 cm", "15.0 cm", "17.5 cm", "20.0 cm", "22.5 cm", "25.0 cm", "27.5 cm", "30.0 cm" }));
        jPanel14.add(separacion3);

        jLabel96.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel96.setText("As");
        jPanel14.add(jLabel96);

        as3.setEditable(false);
        as3.setBackground(new java.awt.Color(204, 204, 204));
        as3.setText("1.0");
        jPanel14.add(as3);
        jPanel14.add(jLabel97);
        jPanel14.add(jLabel98);

        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel99.setText("Ld propuesto");
        jPanel14.add(jLabel99);

        ld_propuesto2.setEditable(false);
        ld_propuesto2.setBackground(new java.awt.Color(204, 204, 204));
        ld_propuesto2.setText("1.0");
        jPanel14.add(ld_propuesto2);

        jLabel100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel100.setText("Ld");
        jPanel14.add(jLabel100);

        ld2.setText("1.0");
        jPanel14.add(ld2);

        jLabel101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel101.setText("ϕMr");
        jPanel14.add(jLabel101);

        fi_mr3.setEditable(false);
        fi_mr3.setBackground(new java.awt.Color(204, 204, 204));
        fi_mr3.setText("1.0");
        jPanel14.add(fi_mr3);
        jPanel14.add(jLabel102);
        jPanel14.add(jLabel103);

        jPanel10.add(jPanel14);

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "As Temp", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel23.setLayout(new java.awt.GridLayout(4, 2, 2, 2));

        jLabel23.setText("Varillas");
        jPanel23.add(jLabel23);

        varillas4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1#3 = 0.71 cm²", "1#4 = 1.27 cm²", "1#5= 1.98 cm²", "1#6 = 2.85 cm² ", "1#8 = 5.07 cm²", "1#10 = 7.92 cm²", "1#12 = 11.40 cm²" }));
        jPanel23.add(varillas4);

        jLabel29.setText("Separación");
        jPanel23.add(jLabel29);

        separacion4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2.5 cm", "5.0 cm", "7.5 cm", "10.0 cm", "12.5 cm", "15.0 cm", "17.5 cm", "20.0 cm", "22.5 cm", "25.0 cm", "27.5 cm", "30.0 cm" }));
        jPanel23.add(separacion4);

        jLabel30.setText("As");
        jPanel23.add(jLabel30);

        as4.setEditable(false);
        as4.setBackground(new java.awt.Color(204, 204, 204));
        as4.setText("1.0");
        jPanel23.add(as4);
        jPanel23.add(jLabel32);
        jPanel23.add(jLabel33);

        jPanel10.add(jPanel23);

        jPanel27.add(jPanel10);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Revisión", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jPanel18.setLayout(new java.awt.GridLayout(1, 5, 2, 2));

        jLabel125.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel125.setText("ΣϕMr");
        jPanel18.add(jLabel125);

        sum_fi_mr.setEditable(false);
        sum_fi_mr.setBackground(new java.awt.Color(204, 204, 204));
        sum_fi_mr.setText("0.0");
        jPanel18.add(sum_fi_mr);

        jLabel126.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel126.setText(">");
        jPanel18.add(jLabel126);

        jLabel129.setText("Mmax");
        jPanel18.add(jLabel129);

        m_max.setEditable(false);
        m_max.setBackground(new java.awt.Color(204, 204, 204));
        m_max.setText("0.0");
        jPanel18.add(m_max);

        jPanel17.add(jPanel18);

        jPanel19.setLayout(new java.awt.GridLayout(1, 5, 2, 2));

        jLabel127.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel127.setText("ϕVc");
        jPanel19.add(jLabel127);

        fi_vc.setEditable(false);
        fi_vc.setBackground(new java.awt.Color(204, 204, 204));
        fi_vc.setText("0.0");
        jPanel19.add(fi_vc);

        jLabel128.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel128.setText(">");
        jPanel19.add(jLabel128);

        jLabel130.setText("Vmax");
        jPanel19.add(jLabel130);

        v_max.setEditable(false);
        v_max.setBackground(new java.awt.Color(204, 204, 204));
        v_max.setText("0.0");
        jPanel19.add(v_max);

        jPanel17.add(jPanel19);

        jPanel28.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel28.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 40, 5));

        buttonGroup1.add(momento);
        momento.setSelected(true);
        momento.setText("Momento");
        jPanel28.add(momento);

        buttonGroup1.add(cortante);
        cortante.setText("Cortante");
        jPanel28.add(cortante);

        mostrar.setText("Mostrar");
        jPanel28.add(mostrar);

        jPanel17.add(jPanel28);

        jPanel27.add(jPanel17);

        jScrollPane2.setViewportView(jPanel27);

        getContentPane().add(jScrollPane2);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel73.setText("Nombre del muro: ");
        jPanel9.add(jLabel73);

        name.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel9.add(name);

        aceptar1.setText("Aceptar");
        jPanel9.add(aceptar1);

        cancelar.setText("Cancelar");
        jPanel9.add(cancelar);

        getContentPane().add(jPanel9);

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel21.setLayout(new javax.swing.BoxLayout(jPanel21, javax.swing.BoxLayout.X_AXIS));

        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel22.add(combo_almacen);

        jPanel21.add(jPanel22);

        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        guardar.setText("Guardar");
        jPanel20.add(guardar);

        editar.setText("Editar");
        jPanel20.add(editar);

        eliminar.setText("Eliminar");
        jPanel20.add(eliminar);

        cerrar.setText("Cerrar");
        jPanel20.add(cerrar);

        jPanel21.add(jPanel20);

        getContentPane().add(jPanel21);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField a1;
    public javax.swing.JButton aceptar1;
    public javax.swing.JButton aceptar_1;
    public javax.swing.JTextField alpha;
    public javax.swing.JTextField as1;
    public javax.swing.JTextField as2;
    public javax.swing.JTextField as3;
    public javax.swing.JTextField as4;
    public javax.swing.JTextField beta;
    public javax.swing.JTextField beta1;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JTextField c;
    public javax.swing.JButton cancelar;
    public javax.swing.JButton cerrar;
    public javax.swing.JComboBox<String> combo1;
    public javax.swing.JComboBox<String> combo_almacen;
    public javax.swing.JTextField constante1;
    public javax.swing.JTextField constante2;
    public javax.swing.JRadioButton cortante;
    public javax.swing.JTextField d1;
    public javax.swing.JTextField d2;
    public javax.swing.JTextField delta;
    public javax.swing.JButton editar;
    public javax.swing.JButton eliminar;
    public javax.swing.JTextField fc;
    public javax.swing.JTextField fi1;
    public javax.swing.JTextField fi2;
    public javax.swing.JTextField fi_f;
    public javax.swing.JTextField fi_mr1;
    public javax.swing.JTextField fi_mr2;
    public javax.swing.JTextField fi_mr3;
    public javax.swing.JTextField fi_v;
    public javax.swing.JTextField fi_vc;
    public javax.swing.JTextField fs_desliz;
    public javax.swing.JTextField fs_v;
    public javax.swing.JTextField fy;
    public javax.swing.JTextField gamma1;
    public javax.swing.JTextField gamma2;
    public javax.swing.JButton guardar;
    public javax.swing.JTextField h1;
    public javax.swing.JTextField h2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    public javax.swing.JLabel jLabel108;
    public javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel110;
    public javax.swing.JLabel jLabel111;
    public javax.swing.JLabel jLabel112;
    public javax.swing.JLabel jLabel113;
    public javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    public javax.swing.JLabel jLabel_ka1;
    public javax.swing.JLabel jLabel_ka2;
    public javax.swing.JLabel jLabel_kp1;
    public javax.swing.JLabel jLabel_kp2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField ka1;
    public javax.swing.JTextField ka2;
    public javax.swing.JTextField kh;
    public javax.swing.JTextField kp1;
    public javax.swing.JTextField kp2;
    public javax.swing.JTextField kv;
    public javax.swing.JTextField l1;
    public javax.swing.JTextField l2;
    public javax.swing.JTextField l3;
    public javax.swing.JTextField ld1;
    public javax.swing.JTextField ld2;
    public javax.swing.JTextField ld_propuesto1;
    public javax.swing.JTextField ld_propuesto2;
    public javax.swing.JTextField m;
    public javax.swing.JTextField m_max;
    public javax.swing.JRadioButton momento;
    public javax.swing.JButton mostrar;
    public javax.swing.JTextField mpp;
    public javax.swing.JTextField mwa;
    public javax.swing.JTextField mwp;
    public javax.swing.JTextField name;
    public javax.swing.JTextField next_to_qmin;
    public javax.swing.JTextField p_propio;
    public javax.swing.JTextField pa;
    public javax.swing.JTextField pae;
    public javax.swing.JTextField q_max;
    public javax.swing.JTextField q_min;
    public javax.swing.JTextField qad;
    public javax.swing.JTextField qad_espejo;
    public javax.swing.JComboBox<String> r;
    public javax.swing.JTextField rho_bal;
    public javax.swing.JTextField rho_max;
    public javax.swing.JTextField sc;
    public javax.swing.JComboBox<String> separacion1;
    public javax.swing.JComboBox<String> separacion2;
    public javax.swing.JComboBox<String> separacion3;
    public javax.swing.JComboBox<String> separacion4;
    public javax.swing.JTextField sum_fi_mr;
    public javax.swing.JTextField sum_v;
    public javax.swing.JTextField v_max;
    public javax.swing.JTextField var_e;
    public javax.swing.JTextField variacion_pae;
    public javax.swing.JComboBox<String> varillas1;
    public javax.swing.JComboBox<String> varillas2;
    public javax.swing.JComboBox<String> varillas3;
    public javax.swing.JComboBox<String> varillas4;
    public javax.swing.JTextField wa;
    public javax.swing.JTextField wp;
    // End of variables declaration//GEN-END:variables
}
